// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTgdTmerxd0oQFVHhZMHda-q4_9_06f0',
    appId: '1:375034192591:web:c5d0a13fb3ce0bc5ca8dba',
    messagingSenderId: '375034192591',
    projectId: 'flutter-instagram-599bd',
    authDomain: 'flutter-instagram-599bd.firebaseapp.com',
    storageBucket: 'flutter-instagram-599bd.appspot.com',
    measurementId: 'G-VMD829K5PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5hiCyyvi2vA9Is5jsZ4OOa41sB-VkLc',
    appId: '1:375034192591:android:4686cbd8ed5e01a3ca8dba',
    messagingSenderId: '375034192591',
    projectId: 'flutter-instagram-599bd',
    storageBucket: 'flutter-instagram-599bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOhoK33K1e3Df-QKZjW3zgrOTlHOCbkRU',
    appId: '1:375034192591:ios:c3582225019fd133ca8dba',
    messagingSenderId: '375034192591',
    projectId: 'flutter-instagram-599bd',
    storageBucket: 'flutter-instagram-599bd.appspot.com',
    iosBundleId: 'app.hristov.instagram',
  );
}
