name: instagram
description: Flutter Instagram app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_mappr_annotation: ^2.1.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.11.0
  either_dart: ^1.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  event_bus: ^2.0.0
  firebase_analytics: ^10.6.1
  firebase_auth: ^4.11.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  meta: ^1.9.0
  strings: ^2.0.3
  timeago: ^3.5.0
  uuid: ^4.1.0

dev_dependencies:
  auto_mappr: ^2.1.1
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
